server:
  port: 6789
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-api-sample
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://27.115.74.130:3306/syhk_data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: syhk888.
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000

  redis:
    host: 27.115.74.130
    port: 6379
    database: 0
    username: # if you enable
    password: adminsyhk@123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

jwt:
  issuer: DJI
  subject: CloudApiSample
  secret: CloudApiSample
  age: 86400

mqtt:
  # @see com.dji.sample.component.mqtt.model.MqttUseEnum
  # BASIC parameters are required.
  BASIC:
    protocol: MQTT # @see com.dji.sample.component.mqtt.model.MqttProtocolEnum
    host: 27.115.74.130
    port: 1883
    username: Francis
    password: admin
    client-id: 199957
    # If the protocol is ws/wss, this value is required.
    path:
  DRC:
    protocol: WS # @see com.dji.sample.component.mqtt.model.MqttProtocolEnum
    host: 27.115.74.130
    port: 8083
    path: /mqtt

cloud-sdk:
  mqtt:
    # Topics that need to be subscribed when initially connecting to mqtt, multiple topics are divided by ",".
    inbound-topic: sys/product/+/status,thing/product/+/requests

url:
  manage:
    prefix: manage
    version: /api/v1
  map:
    prefix: map
    version: /api/v1
  media:
    prefix: media
    version: /api/v1
  wayline:
    prefix: wayline
    version: /api/v1
  storage:
    prefix: storage
    version: /api/v1
  control:
    prefix: control
    version: /api/v1

# Tutorial: https://www.alibabacloud.com/help/en/object-storage-service/latest/use-a-temporary-credential-provided-by-sts-to-access-oss
oss:
  enable: true
  provider: minio
  endpoint: http://27.115.74.130:9000
  access-key: admin
  secret-key: admin123
  expire: 3600
  region: us-east-1
  bucket: syhk-web-prod
  object-dir-prefix: wayline
  #minio控制台接口地址
  minio-console-api: http://27.115.74.130:9001

#oss:
#  enable: true
#  provider: aws
#  endpoint: https://s3.us-east-1.amazonaws.com
#  access-key:
#  secret-key:
#  expire: 3600
#  region: us-east-1
#  role-session-name: cloudApi
#  role-arn:
#  bucket: cloudapi-bucket
#  object-dir-prefix: wayline

#oss:
#  enable: true
#  provider: minio
#  endpoint: http://192.168.1.1:9000
#  access-key: minioadmin
#  secret-key: minioadmin
#  bucket: cloud-bucket
#  expire: 3600
#  region: us-east-1
#  object-dir-prefix: wayline

# 日志配置
logging:
  level:
    com.dji: debug
    org.springframework: warn

ntp:
  server:
    host: ntp1.aliyun.com

# To create a license for an application: https://developer.dji.com/user/apps/#all
cloud-api:
  app:
    id: 138652
    key: b0efdc65fcfbf96c8fa97d8e493dccf
    license: S+aBaLLeqt8rzfsXFooiPJ63/X/48969ZaTRZsv+DZwzP8m70xsFjnAzqTQGuo4FOPN9q7bRFFARNOYv71hIhGvge0tdKZUtw2GuK0dhHM9F1RFseSbqi5KNvbhHsgD/L+J6cuMsZMBrt7/78Aoi8p1EMDhnkIdF3njbu8Pax5U=

# 流媒体服务
live:
  api: http://27.115.74.130:3090/api
  secret: 3ec62d2b-4195-e8bc-deb8-dcb7a37e68d0
  url: rtmp://27.115.74.130:3080ream=